/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

group = "hexlet.code"
version = "1.0-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

plugins {
    id("application")
    id("checkstyle")
    id("se.patrikerdes.use-latest-versions") version "0.2.18"
    id("com.github.ben-manes.versions") version "0.49.0"
    id("com.gradleup.shadow") version "8.3.10"
    id("io.freefair.lombok") version "8.10"
    id("org.sonarqube") version "4.0.0.2929"
    id("jacoco")
}

dependencies {
    // https://mvnrepository.com/artifact/io.javalin/javalin
    implementation("io.javalin:javalin:6.6.0")
    // https://mvnrepository.com/artifact/io.javalin/javalin-bundle
    implementation("io.javalin:javalin-bundle:6.6.0")
    implementation("io.javalin:javalin-rendering:6.6.0")
    implementation("org.slf4j:slf4j-simple:1.7.31")
    implementation("com.zaxxer:HikariCP:5.0.1")
    implementation("com.h2database:h2:2.3.232")
    testImplementation(platform("org.junit:junit-bom:5.9.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.assertj:assertj-core:3.22.0")
    implementation("org.postgresql:postgresql:42.7.7")
    implementation("gg.jte:jte:3.2.1")
    implementation("com.konghq:unirest-java-core:4.5.0")
    implementation("org.jsoup:jsoup:1.21.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
}

application {
    mainClass.set("hexlet.code.App")
}

checkstyle {
    toolVersion = "10.9.3"

    configFile = file("../config/checkstyle/checkstyle.xml")

    isIgnoreFailures = true
    maxWarnings = 0
    maxErrors = 0
}

jacoco {
    toolVersion = "0.8.12"
}

sonar {
    properties {
        property("sonar.projectName", "Hexlet.Java.m4k.PageAnalyzer")
        property("sonar.projectKey", "AnrDaemon_java-project-72")
        property("sonar.organization", "anrdaemon")
        property("sonar.host.url", "https://sonarcloud.io")
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.9.3")

            targets.all {
                testTask.configure {
                    finalizedBy(tasks.jacocoTestReport)
                }
            }
        }
    }
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to application.mainClass.get(),
            "Implementation-Title" to "Page analyzer course work",
            "Implementation-Version" to project.version
        )
    }
}

tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(arrayOf(
        "-Aproject=${project.group}/${project.name}"
    ))
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        csv.required.set(false)
    }
}

tasks.register("install") {
    dependsOn("installDist")
}
